services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: pt-fsdj-mysql-container
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: PT_FSDJ
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - ./database-init:/docker-entrypoint-initdb.d
  #     - mysql-data:/var/lib/mysql
  #   network_mode: host

  backend:
    build: ./backend
    container_name: pt-fsdj-backend-container
    environment:
      - DB_USER=prueba_tec_admin
      - DB_PASSWORD=pt_fsdj_1$
      - DB_DATABASE=PT_FSDJ
      - DB_SERVER=prueba-tec-fullstack-server.mysql.database.azure.com
      - DB_PORT=
      - PORT=3080
      - API_STRUCTURE=api
      - LOGIN_TOKEN=mYtoKenForSPtLvLogin_$
    ports:
      - "4080:3080"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: pt-fsdj-frontend-container
    environment:
      - DB_USER=user
      - VITE_API_STRUCTURE=api
      - VITE_API_DOMAIN=http://localhost:4080
    ports:
      - "5174:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
    driver: local
